apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: install-cluster
  namespace: flux-system
  labels:
    flux-demo: "yes"
spec:
  interval: 10s
  path: ./cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo
  validation: client
