apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: install-managed-app
  namespace: flux-system
  labels:
    flux-demo: "yes"
spec:
  interval: 1m0s
  path: ./managed-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo
  validation: client
