apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: install-cluster-chart
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: "./cluster-chart"
      sourceRef:
        kind: GitRepository
        name: flux-demo
        namespace: flux-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
