apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flux-nginx
  name: flux-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-nginx
  template:
    metadata:
      labels:
        app: flux-nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
